@startuml

title __REPOSITORY's Class Diagram__\n

  namespace  {
    namespace ci.travel_app.walkthebear {
      namespace repository {
        interface sci.travel_app.walkthebear.repository.AppUserRepository {
            {abstract} + findAll()
            {abstract} + findByEmail()
            {abstract} + findById()
            {abstract} + findByUserName()
            {abstract} + findByUserNameAndPassword()
            {abstract} + findUsersByKeyword()
        }
      }
    }
  }
  

  namespace  {
    namespace ci.travel_app.walkthebear {
      namespace repository {
        interface sci.travel_app.walkthebear.repository.DailyScheduleRepository {
            {abstract} + findById()
            {abstract} + findByItinerary()
            {abstract} + findByNameAndItinerary()
        }
      }
    }
  }
  

  namespace  {
    namespace ci.travel_app.walkthebear {
      namespace repository {
        interface sci.travel_app.walkthebear.repository.FavoritesRepository {
            {abstract} + findById()
            {abstract} + findByPlace()
            {abstract} + findByPlaceAndUser()
            {abstract} + findByUser()
            {abstract} + getPlacesFromFav()
        }
      }
    }
  }
  

  namespace  {
    namespace ci.travel_app.walkthebear {
      namespace repository {
        interface sci.travel_app.walkthebear.repository.HourMappingRepository {
            {abstract} + findByDailySchedule()
            {abstract} + findById()
        }
      }
    }
  }
  

  namespace  {
    namespace ci.travel_app.walkthebear {
      namespace repository {
        interface sci.travel_app.walkthebear.repository.ItineraryRepository {
            {abstract} + findById()
            {abstract} + findByUser()
        }
      }
    }
  }
  

  namespace  {
    namespace ci.travel_app.walkthebear {
      namespace repository {
        interface sci.travel_app.walkthebear.repository.PlacesRepository {
            {abstract} + findAll()
            {abstract} + findAllByOrderByCreatedDesc()
            {abstract} + findByCategory()
            {abstract} + findByCategory()
            {abstract} + findByCity()
            {abstract} + findByCounty()
            {abstract} + findById()
            {abstract} + findByKeyword()
            {abstract} + findByName()
            {abstract} + findByNameContains()
            {abstract} + findBySubcategory()
            {abstract} + findBySubcategoryAndCity()
            {abstract} + findBySubcategoryAndCounty()
            {abstract} + findBySubcategoryAndCountyAndCity()
            {abstract} + findPlaceByUser()
        }
      }
    }
  }
  

  namespace  {
    namespace ci.travel_app.walkthebear {
      namespace repository {
        interface sci.travel_app.walkthebear.repository.RatingRepository {
            {abstract} + findAll()
            {abstract} + findById()
            {abstract} + findByPlace()
            {abstract} + findByPlaceAndUser()
            {abstract} + findByUser()
        }
      }
    }
  }
  

  namespace  {
    namespace ci.travel_app.walkthebear {
      namespace repository {
        interface sci.travel_app.walkthebear.repository.UnplannedPlacesListRepository {
            {abstract} + findById()
            {abstract} + findByUser()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
