package sci.travel_app.WalkTheBear.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;
import sci.travel_app.WalkTheBear.model.entities.AppUser;
import sci.travel_app.WalkTheBear.model.misc.AppUserRole;
import sci.travel_app.WalkTheBear.repository.AppUserRepository;

@Controller
public class AppUserController {


    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AppUserRepository userRepository;

    @PostMapping(path = "/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewUser(@RequestParam String userName, @RequestParam String password, @RequestParam String email, @RequestParam AppUserRole role) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        AppUser n = new AppUser();
        n.setUserName(userName);
        n.setPassword(password);
        n.setEmail(email);
        n.setRole(role);


        userRepository.save(n);
        return "Saved";
    }

    @GetMapping(value = "/greeting")

    public ModelAndView captureDetails() {
        ModelAndView mav = new ModelAndView("adduser");

        AppUser theuser = new AppUser();
        theuser.setUserName("fffff");
        theuser.setPassword("ffff");
        theuser.setEmail("ffff");
        theuser.setRole(AppUserRole.HOST);


        mav.addObject("theuser", theuser);
        return mav;
    }

    //@Autowired
    //private sci.travel_app.WalkTheBear.service.AppUserService appUserService;

    //@Autowired
    //private AppUserValidator appUserValidator;

    //@RequestMapping("/")
    //public String index() {
       //return "index";
    //}

   /* @RequestMapping("/login")
    public String login(Model model) {
        model.addAttribute("classActiveLogin", true);
        return "myAccount";
    }
*/
   /* @GetMapping("/registration")
    public String registration(Model model) {
        model.addAttribute("register", new User());

        return "registration";
    }
*/
  /*  //1 attempt registration-- role??
    @PostMapping("/registration")
    public String registration(@ModelAttribute("registerUser") AppUser registerUser, BindingResult bindingResult) {
        appUserValidator.validate(registerUser, bindingResult);

        if (bindingResult.hasErrors()) {
            return "registration";
        }

        appUserService.save(registerUser);

        //  securityService.autoLogin(userForm.getUserName(), userForm.getPasswordConfirm());

        return "redirect:/index";
    }*/


//        @GetMapping(path = "/all")
//        public @ResponseBody
//        Iterable<AppUser> getAllUsers() {
//            // This returns a JSON or XML with the users
//
//            return "adduser";
//        }

}