package sci.travel_app.walkthebear.controller;


import org.apache.tomcat.jni.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import sci.travel_app.walkthebear.repository.AppUserRepository;

@Controller
public class AppUserController {


    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AppUserRepository userRepository;

//    @Autowired
//    private BCryptPasswordEncoder passwordEncoder;
//
//    @Autowired
//    private sci.travel_app.WalkTheBear.service.AppUserServiceImp appUserService;
//
//    @Autowired
//    private AppUserValidator appUserValidator;


//moved to HomePageController
//    @RequestMapping("/")
//    public String index() {
//        return "index";
//    }

    @RequestMapping("/login")
    public String login(Model model) {
        model.addAttribute("classActiveLogin", true);
        return "login";
    }


    @GetMapping("/registration")
    public String registration(Model model) {
        model.addAttribute("register", new User());

        return "registration";

    }
}